image: python:3.8-buster

install_packages:
  stage: 
    - test
    - deploy
  script:
  - pip install mkdocs mkdocs-material pymdown-extensions pyembed-markdown


docs_test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - main
stages:
- test
- deploy
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
