variables:
  IMAGE_REF: python:3.8-buster

.install_packages: $install_packages
  - pip install mkdocs mkdocs-material pymdown-extensions pyembed-markdown

docs_test:
  image: $IMAGE_REF
  script:
  - <<:*install_packages
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  image: $IMAGE_REF
  script:
  - <<:*install_packages
  - mkdocs build --strict --verbose
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - main

include:
- template: Security/SAST.gitlab-ci.yml
